service: hello-lambda-test

frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x
  region: us-east-1

functions:
  hello:
    handler: handler.hello
    environment:
      USER_NAME: ${env:USER_NAME}
      PASSWORD: ${env:PASSWORD}
    events:
      - http:
          path: hello
          method: get
